# Generated by Django 4.2.6 on 2024-03-18 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenerURLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(max_length=50, verbose_name='Тема')),
                ('long_link', models.CharField(max_length=255, verbose_name='Длинный URL')),
                ('short_link', models.CharField(max_length=10, verbose_name='Короткий URL')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR-код')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
