# Generated by Django 4.2.6 on 2024-03-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenerurlmodel',
            name='short_link',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='Короткий URL'),
        ),
    ]
