# Generated by Django 4.2.6 on 2024-03-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmclockmodel',
            name='hint',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
