# Generated by Django 4.2.6 on 2024-03-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_alter_alarmclockmodel_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmclockmodel',
            name='alarm_time',
            field=models.CharField(max_length=5, unique=True, verbose_name='Время'),
        ),
    ]
